name: crane-installer
author: Kyle Colantonio
description: GitHub Action for installing the crane CLI tool

branding:
  icon: package
  color: red

inputs:
  crane-release:
    description: crane release version to be installed
    required: false
    default: latest
  verify:
    description: Perform signature verification on crane
    required: false
    default: 'true'
  cache:
    description: Whether to utilize cache with crane
    required: false
    default: 'true'
  token:
    description: GitHub token for REST API access
    required: false
    default: ${{ github.token }}

outputs:
  version:
    description: The version of crane that was installed
  cache-hit:
    description: If crane was installed via cache

runs:
  using: node24
  main: dist/index.js
