name: Main

on:
  push:
    branches:
      - main

jobs:
  test:
    name: Test crane-installer Action
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install crane
        uses: ./

      - name: Test crane
        run: |
          crane version
          crane ls caddy
          crane digest nginx:latest
          crane config alpine:3.11

  main:
    name: Publish new version
    runs-on: ubuntu-latest
    needs: [test]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Bump version tag
        id: tag
        uses: mathieudutour/github-tag-action@v6.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Update shared tags
        run: |
          MAJOR=$(echo ${{ steps.tag.outputs.new_version }} | cut -d . -f 1)
          MINOR=$(echo ${{ steps.tag.outputs.new_version }} | cut -d . -f 2)
          git tag -f v$MAJOR
          git tag -f v$MAJOR.$MINOR
          git push -f -u origin v$MAJOR
          git push -f -u origin v$MAJOR.$MINOR
