name: Action Test & Release

on:
  push:
    branches: [main]
    paths:
      - .github/workflows/main.yml
      - action.yml
  pull_request:
    branches: [main]
    paths:
      - .github/workflows/main.yml
      - action.yml

jobs:
  test:
    name: Test action
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        slsa: [true, false]

    steps:
      - name: Checkout repo
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: Install SLSA verifier
        uses: slsa-framework/slsa-verifier/actions/installer@3714a2a4684014deb874a0e737dffa0ee02dd647 # v2.6.0
        if: matrix.slsa && runner.os == 'Linux' # doesn't work on Windows or macOS

      - name: Install crane
        uses: ./
        with:
          crane-release: v0.19.1

      - name: Test crane
        run: crane version

  main:
    if: ${{ github.event_name == 'push' }}
    name: Publish new version
    runs-on: ubuntu-latest
    needs: [test]
    steps:
      - name: Checkout repo
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: Bump version tag
        id: tag
        uses: mathieudutour/github-tag-action@a22cf08638b34d5badda920f9daf6e72c477b07b # v6.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Update shared tags
        run: |
          MAJOR=$(echo ${{ steps.tag.outputs.new_version }} | cut -d . -f 1)
          MINOR=$(echo ${{ steps.tag.outputs.new_version }} | cut -d . -f 2)
          git tag -f v$MAJOR
          git tag -f v$MAJOR.$MINOR
          git push -f -u origin v$MAJOR
          git push -f -u origin v$MAJOR.$MINOR

      - name: Create GitHub release
        uses: softprops/action-gh-release@c062e08bd532815e2082a85e87e3ef29c3e6d191 # v2.0.8
        with:
          tag_name: v${{ steps.tag.outputs.new_version }}
          make_latest: true
          generate_release_notes: true
